trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'TestCaseExecutor/**'
    - 'builds/**'

pool:
  name: Studer

variables:
  major: 2.0
  minor: $[counter(variables['major'], 0)]
  semver: $(major).$(minor)

steps:
- task: PowerShell@2
  displayName: Set the name of the pipeline run
  inputs:
    targetType: inline
    script: Write-Host "##vso[build.updatebuildnumber]$(semver)"

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET 8.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build and Publish'
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration Release -r win-x64 --self-contained true --framework net8.0-windows7.0 --output .\publish /p:Version=$(semver)'
    zipAfterPublish: false

- task: BatchScript@1
  displayName: Build installer
  inputs:
    filename: '"C:\Program Files (x86)\Inno Setup 6\iscc"'
    arguments: 'builds\buildSetup.iss /dMyAppVersion=$(semver) /dOutputDir="$(build.artifactstagingdirectory)"'
    workingFolder: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish installer'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'TestCaseExecutor_$(semver)'
  condition: succeeded()